import { execFileSync } from "node:child_process"
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

// The version the side panel shows. The script runs inside SynthV with nothing
// to ask, so whatever identifies this build has to be written into it here.
//
// A release build is one whose commit carries a tag, or one made outside a
// checkout at all (a source archive, a packaging step that dropped .git) — that
// is the app's own version. Anything else is somebody's working copy, where the
// version number has not moved and the commit is the only honest answer.

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const target = join(root, "src", "lua", "version.ts")

function git(...args) {
  try {
    return execFileSync("git", args, {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim()
  } catch {
    return null
  }
}

function appVersion() {
  const manifest = join(root, "..", "..", "apps", "karaoke-v", "package.json")
  return JSON.parse(readFileSync(manifest, "utf8")).version
}

function describe() {
  const head = git("rev-parse", "--short", "HEAD")
  if (!head) {
    return appVersion()
  }
  if (git("describe", "--exact-match", "--tags", "HEAD")) {
    return appVersion()
  }
  return git("status", "--porcelain") ? `dev ${head}-dirty` : `dev ${head}`
}

const contents = `// Generated by scripts/version.mjs. Not edited, not committed.
export const SCRIPT_VERSION = ${JSON.stringify(describe())}
`

// Rewriting an identical file would only invalidate the build for nothing.
try {
  if (readFileSync(target, "utf8") === contents) {
    process.exit(0)
  }
} catch {}

writeFileSync(target, contents)
